"""
pyratatui type stubs.

This file provides complete type information for IDEs and type checkers.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Callable

# ── Module metadata ──────────────────────────────────────────────────────────

__version__: str
__ratatui_version__: str

# ── Exceptions ───────────────────────────────────────────────────────────────

class PyratatuiError(Exception): ...
class BackendError(PyratatuiError): ...
class LayoutError(PyratatuiError): ...
class RenderError(PyratatuiError): ...
class AsyncError(PyratatuiError): ...
class StyleError(PyratatuiError): ...

# ── Color ────────────────────────────────────────────────────────────────────

class Color:
    @staticmethod
    def reset() -> Color: ...
    @staticmethod
    def black() -> Color: ...
    @staticmethod
    def red() -> Color: ...
    @staticmethod
    def green() -> Color: ...
    @staticmethod
    def yellow() -> Color: ...
    @staticmethod
    def blue() -> Color: ...
    @staticmethod
    def magenta() -> Color: ...
    @staticmethod
    def cyan() -> Color: ...
    @staticmethod
    def gray() -> Color: ...
    @staticmethod
    def dark_gray() -> Color: ...
    @staticmethod
    def light_red() -> Color: ...
    @staticmethod
    def light_green() -> Color: ...
    @staticmethod
    def light_yellow() -> Color: ...
    @staticmethod
    def light_blue() -> Color: ...
    @staticmethod
    def light_magenta() -> Color: ...
    @staticmethod
    def light_cyan() -> Color: ...
    @staticmethod
    def white() -> Color: ...
    @staticmethod
    def indexed(index: int) -> Color: ...
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Color: ...

# ── Modifier ─────────────────────────────────────────────────────────────────

class Modifier:
    def __init__(self) -> None: ...
    @staticmethod
    def bold() -> Modifier: ...
    @staticmethod
    def dim() -> Modifier: ...
    @staticmethod
    def italic() -> Modifier: ...
    @staticmethod
    def underlined() -> Modifier: ...
    @staticmethod
    def slow_blink() -> Modifier: ...
    @staticmethod
    def rapid_blink() -> Modifier: ...
    @staticmethod
    def reversed() -> Modifier: ...
    @staticmethod
    def hidden() -> Modifier: ...
    @staticmethod
    def crossed_out() -> Modifier: ...
    def __or__(self, other: Modifier) -> Modifier: ...
    def __and__(self, other: Modifier) -> Modifier: ...

# ── Style ────────────────────────────────────────────────────────────────────

class Style:
    def __init__(self) -> None: ...
    def fg(self, color: Color) -> Style: ...
    def bg(self, color: Color) -> Style: ...
    def add_modifier(self, modifier: Modifier) -> Style: ...
    def remove_modifier(self, modifier: Modifier) -> Style: ...
    def patch(self, other: Style) -> Style: ...
    def bold(self) -> Style: ...
    def italic(self) -> Style: ...
    def underlined(self) -> Style: ...
    def dim(self) -> Style: ...
    def reversed(self) -> Style: ...
    def hidden(self) -> Style: ...
    def crossed_out(self) -> Style: ...
    def slow_blink(self) -> Style: ...
    def rapid_blink(self) -> Style: ...
    @property
    def foreground(self) -> Color | None: ...
    @property
    def background(self) -> Color | None: ...

# ── Text primitives ───────────────────────────────────────────────────────────

class Span:
    def __init__(self, content: str, style: Style | None = None) -> None: ...
    @property
    def content(self) -> str: ...
    @property
    def style(self) -> Style | None: ...
    def styled(self, style: Style) -> Span: ...
    def width(self) -> int: ...

class Line:
    def __init__(
        self, spans: list[Span] | None = None, style: Style | None = None
    ) -> None: ...
    @staticmethod
    def from_string(s: str) -> Line: ...
    def left_aligned(self) -> Line: ...
    def centered(self) -> Line: ...
    def right_aligned(self) -> Line: ...
    def styled(self, style: Style) -> Line: ...
    def push_span(self, span: Span) -> None: ...
    @property
    def spans(self) -> list[Span]: ...
    def width(self) -> int: ...

class Text:
    def __init__(
        self, lines: list[Line] | None = None, style: Style | None = None
    ) -> None: ...
    @staticmethod
    def from_string(s: str) -> Text: ...
    def push_line(self, line: Line) -> None: ...
    def push_str(self, s: str) -> None: ...
    @property
    def height(self) -> int: ...
    def width(self) -> int: ...
    def centered(self) -> Text: ...
    def right_aligned(self) -> Text: ...
    def styled(self, style: Style) -> Text: ...
    @property
    def lines(self) -> list[Line]: ...

# ── Layout ────────────────────────────────────────────────────────────────────

class Rect:
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def bottom(self) -> int: ...
    @property
    def left(self) -> int: ...
    @property
    def top(self) -> int: ...
    def area(self) -> int: ...
    def is_empty(self) -> bool: ...
    def inner(self, horizontal: int = 1, vertical: int = 1) -> Rect: ...
    def contains(self, other: Rect) -> bool: ...
    def intersection(self, other: Rect) -> Rect | None: ...
    def union(self, other: Rect) -> Rect: ...

class Constraint:
    @staticmethod
    def length(n: int) -> Constraint: ...
    @staticmethod
    def percentage(pct: int) -> Constraint: ...
    @staticmethod
    def fill(n: int) -> Constraint: ...
    @staticmethod
    def min(n: int) -> Constraint: ...
    @staticmethod
    def max(n: int) -> Constraint: ...
    @staticmethod
    def ratio(numerator: int, denominator: int) -> Constraint: ...

class Direction:
    Horizontal: Direction
    Vertical: Direction

class Alignment:
    Left: Alignment
    Center: Alignment
    Right: Alignment

class Layout:
    def __init__(self) -> None: ...
    def constraints(self, constraints: list[Constraint]) -> Layout: ...
    def direction(self, direction: Direction) -> Layout: ...
    def margin(self, margin: int) -> Layout: ...
    def spacing(self, spacing: int) -> Layout: ...
    def flex_mode(self, mode: str) -> Layout: ...
    def split(self, area: Rect) -> list[Rect]: ...

# ── Buffer ────────────────────────────────────────────────────────────────────

class Buffer:
    def __init__(self, area: Rect) -> None: ...
    @property
    def area(self) -> Rect: ...
    def set_string(
        self, x: int, y: int, text: str, style: Style | None = None
    ) -> None: ...
    def set_span(self, x: int, y: int, span: Span) -> None: ...
    def get_string(self, x: int, y: int, width: int) -> str: ...
    def reset(self) -> None: ...
    def merge(self, other: Buffer) -> None: ...

# ── Widgets ───────────────────────────────────────────────────────────────────

class BorderType:
    Plain: BorderType
    Rounded: BorderType
    Double: BorderType
    Thick: BorderType
    QuadrantInside: BorderType
    QuadrantOutside: BorderType

class Block:
    def __init__(self) -> None: ...
    def title(self, title: str) -> Block: ...
    def title_bottom(self, title: str) -> Block: ...
    def bordered(self) -> Block: ...
    def borders(
        self,
        top: bool = True,
        right: bool = True,
        bottom: bool = True,
        left: bool = True,
    ) -> Block: ...
    def border_type(self, bt: BorderType) -> Block: ...
    def style(self, style: Style) -> Block: ...
    def title_style(self, style: Style) -> Block: ...
    def border_style(self, style: Style) -> Block: ...
    def padding(
        self, left: int = 0, right: int = 0, top: int = 0, bottom: int = 0
    ) -> Block: ...
    def title_alignment(self, alignment: str) -> Block: ...

class Paragraph:
    def __init__(self, text: Text) -> None: ...
    @staticmethod
    def from_string(s: str) -> Paragraph: ...
    def block(self, block: Block) -> Paragraph: ...
    def style(self, style: Style) -> Paragraph: ...
    def wrap(self, wrap: bool = True, trim: bool = True) -> Paragraph: ...
    def scroll(self, y: int = 0, x: int = 0) -> Paragraph: ...
    def alignment(self, alignment: str) -> Paragraph: ...
    def left_aligned(self) -> Paragraph: ...
    def centered(self) -> Paragraph: ...
    def right_aligned(self) -> Paragraph: ...

class ListItem:
    def __init__(self, text: str, style: Style | None = None) -> None: ...
    @staticmethod
    def from_text(text: Text) -> ListItem: ...
    def style(self, style: Style) -> ListItem: ...

class ListState:
    def __init__(self) -> None: ...
    def select(self, index: int | None = None) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    @property
    def selected(self) -> int | None: ...
    @property
    def offset(self) -> int: ...

class ListDirection:
    TopToBottom: ListDirection
    BottomToTop: ListDirection

class List:
    def __init__(self, items: list[ListItem]) -> None: ...
    def block(self, block: Block) -> List: ...
    def style(self, style: Style) -> List: ...
    def highlight_style(self, style: Style) -> List: ...
    def highlight_symbol(self, sym: str) -> List: ...
    def direction(self, direction: ListDirection) -> List: ...
    def repeat_highlight_symbol(self, v: bool) -> List: ...

class Cell:
    def __init__(self, text: str, style: Style | None = None) -> None: ...
    def style(self, style: Style) -> Cell: ...

class Row:
    def __init__(self, cells: list[Cell]) -> None: ...
    @staticmethod
    def from_strings(texts: list[str]) -> Row: ...
    def style(self, style: Style) -> Row: ...
    def height(self, height: int) -> Row: ...

class TableState:
    def __init__(self) -> None: ...
    def select(self, index: int | None = None) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    @property
    def selected(self) -> int | None: ...
    @property
    def offset(self) -> int: ...

class Table:
    def __init__(
        self, rows: list[Row], widths: list[Constraint], header: Row | None = None
    ) -> None: ...
    def block(self, block: Block) -> Table: ...
    def style(self, style: Style) -> Table: ...
    def highlight_style(self, style: Style) -> Table: ...
    def highlight_symbol(self, sym: str) -> Table: ...
    def column_spacing(self, n: int) -> Table: ...
    def footer(self, row: Row) -> Table: ...

class Gauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> Gauge: ...
    def percent(self, pct: int) -> Gauge: ...
    def ratio(self, ratio: float) -> Gauge: ...
    def style(self, style: Style) -> Gauge: ...
    def gauge_style(self, style: Style) -> Gauge: ...
    def label(self, label: str) -> Gauge: ...
    def use_unicode(self, v: bool) -> Gauge: ...

class LineGauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> LineGauge: ...
    def ratio(self, ratio: float) -> LineGauge: ...
    def percent(self, pct: int) -> LineGauge: ...
    def style(self, style: Style) -> LineGauge: ...
    def gauge_style(self, style: Style) -> LineGauge: ...
    def label(self, label: str) -> LineGauge: ...
    def line_set(self, name: str) -> LineGauge: ...

class Bar:
    def __init__(self, value: int, label: str | None = None) -> None: ...
    def style(self, style: Style) -> Bar: ...
    def value_style(self, style: Style) -> Bar: ...
    def text_value(self, tv: str) -> Bar: ...

class BarGroup:
    def __init__(self, bars: list[Bar], label: str | None = None) -> None: ...

class BarChart:
    def __init__(self) -> None: ...
    def data(self, group: BarGroup) -> BarChart: ...
    def block(self, block: Block) -> BarChart: ...
    def bar_width(self, w: int) -> BarChart: ...
    def bar_gap(self, g: int) -> BarChart: ...
    def group_gap(self, g: int) -> BarChart: ...
    def max(self, m: int) -> BarChart: ...
    def style(self, s: Style) -> BarChart: ...
    def bar_style(self, s: Style) -> BarChart: ...
    def value_style(self, s: Style) -> BarChart: ...
    def label_style(self, s: Style) -> BarChart: ...

class Sparkline:
    def __init__(self) -> None: ...
    def data(self, data: list[int]) -> Sparkline: ...
    def block(self, block: Block) -> Sparkline: ...
    def max(self, m: int) -> Sparkline: ...
    def style(self, style: Style) -> Sparkline: ...

class Clear:
    def __init__(self) -> None: ...

class ScrollbarOrientation:
    VerticalRight: ScrollbarOrientation
    VerticalLeft: ScrollbarOrientation
    HorizontalBottom: ScrollbarOrientation
    HorizontalTop: ScrollbarOrientation

class ScrollbarState:
    def __init__(self) -> None: ...
    def content_length(self, n: int) -> ScrollbarState: ...
    def position(self, pos: int) -> ScrollbarState: ...
    def scroll_next(self) -> None: ...
    def scroll_prev(self) -> None: ...
    def first(self) -> None: ...
    def last(self) -> None: ...
    @property
    def get_position(self) -> int: ...

class Scrollbar:
    def __init__(self, orientation: ScrollbarOrientation | None = None) -> None: ...
    def orientation(self, o: ScrollbarOrientation) -> Scrollbar: ...
    def thumb_style(self, st: Style) -> Scrollbar: ...
    def track_style(self, st: Style) -> Scrollbar: ...
    def begin_style(self, st: Style) -> Scrollbar: ...
    def end_style(self, st: Style) -> Scrollbar: ...

class Tabs:
    def __init__(self, titles: list[str]) -> None: ...
    def select(self, index: int) -> Tabs: ...
    def block(self, block: Block) -> Tabs: ...
    def style(self, style: Style) -> Tabs: ...
    def highlight_style(self, style: Style) -> Tabs: ...
    def divider(self, d: str) -> Tabs: ...
    def padding(self, left: str, right: str) -> Tabs: ...

# ── Terminal & Frame ──────────────────────────────────────────────────────────

class KeyEvent:
    code: str
    ctrl: bool
    alt: bool
    shift: bool

class Frame:
    @property
    def area(self) -> Rect: ...
    @property
    def size(self) -> Rect: ...
    def render_widget(self, widget: object, area: Rect) -> None: ...
    def render_stateful_list(
        self, widget: List, area: Rect, state: ListState
    ) -> None: ...
    def render_stateful_table(
        self, widget: Table, area: Rect, state: TableState
    ) -> None: ...
    def render_stateful_scrollbar(
        self, widget: Scrollbar, area: Rect, state: ScrollbarState
    ) -> None: ...
    def apply_effect(self, effect: Effect, elapsed_ms: int, area: Rect) -> None: ...
    def apply_effect_manager(
        self, manager: EffectManager, elapsed_ms: int, area: Rect
    ) -> None: ...
    def render_text_prompt(
        self, prompt: TextPrompt, area: Rect, state: TextState
    ) -> None: ...
    def render_password_prompt(
        self, prompt: PasswordPrompt, area: Rect, state: TextState
    ) -> None: ...
    def render_popup(self, popup: Popup, area: Rect) -> None: ...
    def render_stateful_popup(
        self, popup: Popup, area: Rect, state: PopupState
    ) -> None: ...
    def render_textarea(self, ta: TextArea, area: Rect) -> None: ...
    def render_stateful_scrollview(
        self, sv: ScrollView, area: Rect, state: ScrollViewState
    ) -> None: ...
    def render_qrcode(self, qr: QrCodeWidget, area: Rect) -> None: ...

class CrosstermBackend: ...

class Terminal:
    def __init__(self) -> None: ...
    def __enter__(self) -> Terminal: ...
    def __exit__(self, *args: object) -> bool: ...
    async def __aenter__(self) -> Terminal: ...
    async def __aexit__(self, *args: object) -> bool: ...
    def restore(self) -> None: ...
    def draw(self, draw_fn: Callable[[Frame], None]) -> None: ...
    def poll_event(self, timeout_ms: int = 0) -> KeyEvent | None: ...
    def area(self) -> Rect: ...
    def clear(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...

# ── Python-side helpers ───────────────────────────────────────────────────────

class AsyncTerminal:
    def __init__(self) -> None: ...
    async def __aenter__(self) -> AsyncTerminal: ...
    async def __aexit__(self, *args: object) -> bool: ...
    def draw(self, draw_fn: Callable[[Frame], None]) -> None: ...
    async def poll_event(self, timeout_ms: int = 50) -> KeyEvent | None: ...
    async def events(
        self, fps: float = 30.0, *, stop_on_quit: bool = True
    ) -> AsyncIterator[KeyEvent | None]: ...
    def area(self) -> Rect: ...
    def clear(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...

def run_app(
    ui_fn: Callable[[Frame], None],
    *,
    fps: float = 30.0,
    on_key: Callable[[KeyEvent], bool] | None = None,
) -> None: ...
async def run_app_async(
    ui_fn: Callable[[Frame], None],
    *,
    fps: float = 30.0,
    on_key: Callable[[KeyEvent], bool] | None = None,
) -> None: ...

# ── TachyonFX Effects ─────────────────────────────────────────────────────────

class Interpolation:
    Linear: Interpolation
    QuadIn: Interpolation
    QuadOut: Interpolation
    QuadInOut: Interpolation
    CubicIn: Interpolation
    CubicOut: Interpolation
    CubicInOut: Interpolation
    QuartIn: Interpolation
    QuartOut: Interpolation
    QuartInOut: Interpolation
    QuintIn: Interpolation
    QuintOut: Interpolation
    QuintInOut: Interpolation
    SineIn: Interpolation
    SineOut: Interpolation
    SineInOut: Interpolation
    CircIn: Interpolation
    CircOut: Interpolation
    CircInOut: Interpolation
    ExpoIn: Interpolation
    ExpoOut: Interpolation
    ExpoInOut: Interpolation
    ElasticIn: Interpolation
    ElasticOut: Interpolation
    BounceIn: Interpolation
    BounceOut: Interpolation
    BounceInOut: Interpolation
    BackIn: Interpolation
    BackOut: Interpolation
    BackInOut: Interpolation

class Motion:
    LeftToRight: Motion
    RightToLeft: Motion
    UpToDown: Motion
    DownToUp: Motion

class EffectTimer:
    def __init__(
        self, duration_ms: int, interpolation: Interpolation | None = None
    ) -> None: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def interpolation(self) -> Interpolation: ...

class CellFilter:
    @staticmethod
    def all() -> CellFilter: ...
    @staticmethod
    def text() -> CellFilter: ...
    @staticmethod
    def fg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def bg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def inner(horizontal: int = 1, vertical: int = 1) -> CellFilter: ...
    @staticmethod
    def outer(horizontal: int = 1, vertical: int = 1) -> CellFilter: ...
    @staticmethod
    def all_of(filters: list[CellFilter]) -> CellFilter: ...
    @staticmethod
    def any_of(filters: list[CellFilter]) -> CellFilter: ...

class Effect:
    # Color transitions
    @staticmethod
    def fade_from(
        from_bg: Color,
        from_fg: Color,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def fade_from_fg(
        from_color: Color,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def fade_to(
        to_bg: Color,
        to_fg: Color,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def fade_to_fg(
        to_color: Color, duration_ms: int, interpolation: Interpolation | None = None
    ) -> Effect: ...
    # Text materialization
    @staticmethod
    def coalesce(
        duration_ms: int, interpolation: Interpolation | None = None
    ) -> Effect: ...
    @staticmethod
    def dissolve(
        duration_ms: int, interpolation: Interpolation | None = None
    ) -> Effect: ...
    # Sliding
    @staticmethod
    def slide_in(
        direction: Motion,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def slide_out(
        direction: Motion,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def sweep_in(
        direction: Motion,
        sweep_span: int,
        gradient_len: int,
        color: Color,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    @staticmethod
    def sweep_out(
        direction: Motion,
        sweep_span: int,
        gradient_len: int,
        color: Color,
        duration_ms: int,
        interpolation: Interpolation | None = None,
    ) -> Effect: ...
    # Composition
    @staticmethod
    def sequence(effects: list[Effect]) -> Effect: ...
    @staticmethod
    def parallel(effects: list[Effect]) -> Effect: ...
    @staticmethod
    def sleep(duration_ms: int) -> Effect: ...
    @staticmethod
    def repeat(effect: Effect, times: int = -1) -> Effect: ...
    @staticmethod
    def ping_pong(effect: Effect) -> Effect: ...
    @staticmethod
    def never_complete(effect: Effect) -> Effect: ...
    # Instance methods
    def with_filter(self, filter: CellFilter) -> None: ...
    def process(self, elapsed_ms: int, buffer: Buffer, area: Rect) -> None: ...
    def done(self) -> bool: ...
    def reset(self) -> None: ...

class EffectManager:
    def __init__(self) -> None: ...
    def add(self, effect: Effect) -> None: ...
    def add_unique(self, key: str, effect: Effect) -> None: ...
    def process(self, elapsed_ms: int, buffer: Buffer, area: Rect) -> None: ...
    def active_count(self) -> int: ...
    def clear(self) -> None: ...
    def has_active(self) -> bool: ...

def compile_effect(expression: str) -> Effect: ...

# ── Frame additions ──────────────────────────────────────────────────────────
# (These methods are added to Frame via the prompts module)

# ── PromptStatus ─────────────────────────────────────────────────────────────

class PromptStatus:
    Pending: PromptStatus
    Complete: PromptStatus
    Aborted: PromptStatus

# ── TextRenderStyle ───────────────────────────────────────────────────────────

class TextRenderStyle:
    Normal: TextRenderStyle
    Password: TextRenderStyle
    Invisible: TextRenderStyle

# ── TextState ─────────────────────────────────────────────────────────────────

class TextState:
    def __init__(self, initial: str = "") -> None: ...
    def focus(self) -> None: ...
    def blur(self) -> None: ...
    @property
    def is_focused(self) -> bool: ...
    def value(self) -> str: ...
    def set_value(self, v: str) -> None: ...
    def clear_input(self) -> None: ...
    @property
    def cursor_pos(self) -> int: ...
    @property
    def status(self) -> PromptStatus: ...
    def is_pending(self) -> bool: ...
    def is_complete(self) -> bool: ...
    def is_aborted(self) -> bool: ...
    def reset_status(self) -> None: ...
    def reset(self) -> None: ...
    def handle_key(self, ev: object) -> bool: ...

# ── TextPrompt ────────────────────────────────────────────────────────────────

class TextPrompt:
    def __init__(
        self,
        label: str,
        render_style: TextRenderStyle | None = None,
    ) -> None: ...
    def with_render_style(self, style: TextRenderStyle) -> TextPrompt: ...

# ── PasswordPrompt ────────────────────────────────────────────────────────────

class PasswordPrompt:
    def __init__(self, label: str) -> None: ...

# ── Frame prompt render methods ───────────────────────────────────────────────

# NOTE: These are on Frame — shown here for IDE completion.
# class Frame (additions):
#     def render_text_prompt(self, prompt: TextPrompt, area: Rect, state: TextState) -> None: ...
#     def render_password_prompt(self, prompt: PasswordPrompt, area: Rect, state: TextState) -> None: ...

# ── Blocking helpers ──────────────────────────────────────────────────────────

def prompt_text(label: str) -> str | None:
    """Run a blocking text prompt. Returns the value or None if aborted."""
    ...

def prompt_password(label: str) -> str | None:
    """Run a blocking password prompt. Returns the value or None if aborted."""
    ...

# ═══════════════════════════════════════════════════════════════════════════════
# Popups  (tui-popup integration)
# ═══════════════════════════════════════════════════════════════════════════════

# ── KnownSizeWrapper ──────────────────────────────────────────────────────────

class KnownSizeWrapper:
    """Wrap a list of text lines with explicit width/height for scrollable popups.

    Args:
        lines: List of text lines to display.
        width: Fixed display width of the content area (columns).
        height: Fixed display height of the content area (rows).
        scroll: Initial vertical scroll offset (default 0).

    Example::

        lines = [f"Line {i}" for i in range(20)]
        wrapper = KnownSizeWrapper(lines, width=30, height=8)
        popup = Popup(wrapper).title("Scrollable Content")
    """

    def __init__(
        self,
        lines: list[str],
        width: int,
        height: int,
        scroll: int = 0,
    ) -> None: ...
    def with_scroll(self, scroll: int) -> KnownSizeWrapper: ...
    @property
    def scroll(self) -> int: ...
    def scroll_down(self, n: int) -> None: ...
    def scroll_up(self, n: int) -> None: ...

# ── PopupState ────────────────────────────────────────────────────────────────

class PopupState:
    """State for a draggable/moveable popup.

    Pass to ``frame.render_stateful_popup()`` to enable position tracking.
    Use ``move_*`` for keyboard-driven movement, ``mouse_*`` for mouse drag.

    Example::

        state = PopupState()

        def ui(frame):
            popup = Popup("Hello!").title("Draggable")
            frame.render_stateful_popup(popup, frame.area, state)

        # Move with arrow keys:
        state.move_up(1)
        state.move_down(1)
        state.move_left(1)
        state.move_right(1)
    """

    def __init__(self) -> None: ...
    def move_up(self, n: int) -> None: ...
    def move_down(self, n: int) -> None: ...
    def move_left(self, n: int) -> None: ...
    def move_right(self, n: int) -> None: ...
    def move_to(self, x: int, y: int) -> None: ...
    def mouse_down(self, col: int, row: int) -> None: ...
    def mouse_up(self, col: int, row: int) -> None: ...
    def mouse_drag(self, col: int, row: int) -> None: ...
    def reset(self) -> None: ...

# ── Popup ─────────────────────────────────────────────────────────────────────

class Popup:
    """A centered popup widget.

    Accepts either a plain string body or a ``KnownSizeWrapper`` for
    scrollable content.  Use the builder methods to add a title and style.

    Rendering:

    - **Stateless** (fixed center): ``frame.render_popup(popup, frame.area)``
    - **Stateful** (draggable): ``frame.render_stateful_popup(popup, frame.area, state)``

    Example::

        from pyratatui import Popup, PopupState, Style, Color

        popup = (
            Popup("Press any key to exit")
            .title("tui-popup demo")
            .style(Style().fg(Color.white()).bg(Color.blue()))
        )

        state = PopupState()

        def ui(frame):
            frame.render_stateful_popup(popup, frame.area, state)
    """

    def __init__(self, content: str | KnownSizeWrapper) -> None: ...
    def title(self, title: str) -> Popup: ...
    def style(self, style: Style) -> Popup: ...

# ── Frame popup render methods ────────────────────────────────────────────────

# NOTE: These additions are on the Frame class.
# class Frame (additions):
#     def render_popup(self, popup: Popup, area: Rect) -> None: ...
#     def render_stateful_popup(self, popup: Popup, area: Rect, state: PopupState) -> None: ...

# ═══════════════════════════════════════════════════════════════════════════════
# TextArea  (tui-textarea integration)
# ═══════════════════════════════════════════════════════════════════════════════

# ── CursorMove ────────────────────────────────────────────────────────────────

class CursorMove:
    """Cursor movement command for use with ``TextArea.move_cursor()``."""

    Forward: CursorMove
    Back: CursorMove
    Up: CursorMove
    Down: CursorMove
    WordForward: CursorMove
    WordEnd: CursorMove
    WordBack: CursorMove
    Head: CursorMove
    End: CursorMove
    Top: CursorMove
    Bottom: CursorMove
    ViewportTop: CursorMove
    ViewportMiddle: CursorMove
    ViewportBottom: CursorMove
    ParagraphBack: CursorMove
    ParagraphForward: CursorMove

# ── Scrolling ─────────────────────────────────────────────────────────────────

class Scrolling:
    """Scroll amount for ``TextArea.scroll()``."""

    HalfPageDown: Scrolling
    HalfPageUp: Scrolling
    PageDown: Scrolling
    PageUp: Scrolling
    DeltaDown: Scrolling
    DeltaUp: Scrolling

# ── TextArea ──────────────────────────────────────────────────────────────────

class TextArea:
    """Multi-line text editor widget powered by tui-textarea.

    Supports Emacs-style key bindings, undo/redo, yank/paste, line numbers,
    cursor line highlighting, and text selection.

    Example::

        ta = TextArea.from_lines(["Hello", "World"])
        ta.set_placeholder_text("Type here…")

        with Terminal() as term:
            while True:
                term.draw(lambda frame: frame.render_textarea(ta, frame.area))
                ev = term.poll_event(timeout_ms=50)
                if ev:
                    if ev.code == "Esc": break
                    ta.input_key(ev.code, ev.ctrl, ev.alt, ev.shift)

        print("\\n".join(ta.lines()))
    """

    def __init__(self) -> None: ...
    @staticmethod
    def from_lines(lines: list[str]) -> TextArea: ...

    # Key input
    def input_key(self, code: str, ctrl: bool, alt: bool, shift: bool) -> bool: ...
    def input_without_shortcuts(
        self, code: str, ctrl: bool, alt: bool, shift: bool
    ) -> bool: ...
    def insert_str(self, s: str) -> bool: ...

    # Editing operations
    def delete_char(self) -> bool: ...
    def delete_next_char(self) -> bool: ...
    def insert_newline(self) -> bool: ...
    def delete_line_by_end(self) -> bool: ...
    def delete_line_by_head(self) -> bool: ...
    def delete_word(self) -> bool: ...
    def delete_next_word(self) -> bool: ...

    # Cursor movement
    def move_cursor(self, m: CursorMove) -> None: ...
    def move_cursor_to(self, row: int, col: int) -> None: ...
    def scroll(self, s: Scrolling) -> None: ...

    # Undo/redo/clipboard
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def paste(self) -> bool: ...
    def start_selection(self) -> None: ...
    def cancel_selection(self) -> None: ...
    def cut(self) -> bool: ...
    def copy(self) -> None: ...

    # Accessors
    def lines(self) -> list[str]: ...
    def cursor(self) -> tuple[int, int]: ...
    def is_empty(self) -> bool: ...
    def len(self) -> int: ...
    def selection_range(self) -> tuple[tuple[int, int], tuple[int, int]] | None: ...

    # Styling
    def set_block(self, block: Block) -> None: ...
    def set_cursor_style(self, style: Style) -> None: ...
    def set_cursor_line_style(self, style: Style) -> None: ...
    def set_line_number_style(self, style: Style) -> None: ...
    def remove_line_number(self) -> None: ...
    def set_placeholder_text(self, text: str) -> None: ...
    def set_placeholder_style(self, style: Style) -> None: ...

    # Configuration
    def set_tab_length(self, n: int) -> None: ...
    def set_hard_tab_indent(self, enabled: bool) -> None: ...
    def set_max_histories(self, n: int) -> None: ...

# ── Frame textarea render method ──────────────────────────────────────────────

# NOTE: Addition to Frame class:
# class Frame (additions):
#     def render_textarea(self, ta: TextArea, area: Rect) -> None: ...

# ═══════════════════════════════════════════════════════════════════════════════
# ScrollView  (tui-scrollview integration)
# ═══════════════════════════════════════════════════════════════════════════════

# ── ScrollViewState ───────────────────────────────────────────────────────────

class ScrollViewState:
    """State for a ``ScrollView`` — tracks the current scroll offset.

    Example::

        state = ScrollViewState()

        def ui(frame):
            sv = ScrollView.from_lines(lines, content_width=80)
            frame.render_stateful_scrollview(sv, frame.area, state)

        # Scroll with keys:
        state.scroll_down(1)
        state.scroll_up(1)
        state.scroll_to_top()
    """

    def __init__(self) -> None: ...
    def scroll_down(self, n: int) -> None: ...
    def scroll_up(self, n: int) -> None: ...
    def scroll_right(self, n: int) -> None: ...
    def scroll_left(self, n: int) -> None: ...
    def scroll_to_top(self) -> None: ...
    def scroll_to_bottom(self) -> None: ...
    def reset(self) -> None: ...
    def offset(self) -> tuple[int, int]: ...

# ── ScrollView ────────────────────────────────────────────────────────────────

class ScrollView:
    """A scrollable viewport widget backed by tui-scrollview.

    Create a new ``ScrollView`` each frame from your data, then render it
    with ``frame.render_stateful_scrollview(sv, area, state)``.

    Example::

        lines = [f"  {i:03d} │ data" for i in range(200)]
        state = ScrollViewState()

        sv = ScrollView.from_lines(lines, content_width=80)
        frame.render_stateful_scrollview(sv, frame.area, state)
    """

    def __init__(self, content_width: int, content_height: int) -> None: ...
    @staticmethod
    def from_lines(lines: list[str], content_width: int = 80) -> ScrollView: ...
    def add_paragraph(
        self,
        text: str,
        x: int = 0,
        y: int = 0,
        width: int = 80,
        height: int = 10,
        title: str | None = None,
    ) -> None: ...
    @property
    def content_width(self) -> int: ...
    @property
    def content_height(self) -> int: ...

# ── Frame scrollview render method ────────────────────────────────────────────

# NOTE: Addition to Frame class:
# class Frame (additions):
#     def render_stateful_scrollview(self, sv: ScrollView, area: Rect, state: ScrollViewState) -> None: ...

# ═══════════════════════════════════════════════════════════════════════════════
# QrCode  (tui-qrcode integration)
# ═══════════════════════════════════════════════════════════════════════════════

# ── QrColors ──────────────────────────────────────────────────────────────────

class QrColors:
    """Color scheme for ``QrCodeWidget``."""

    Default: QrColors
    Inverted: QrColors

# ── QrCodeWidget ──────────────────────────────────────────────────────────────

class QrCodeWidget:
    """A QR code widget rendered to the terminal using Unicode block chars.

    Example::

        from pyratatui import QrCodeWidget, QrColors, Terminal

        qr = QrCodeWidget("https://ratatui.rs").colors(QrColors.Inverted)

        with Terminal() as term:
            term.draw(lambda frame: frame.render_qrcode(qr, frame.area))
            term.poll_event(timeout_ms=30_000)
    """

    def __init__(self, data: str) -> None: ...
    def colors(self, colors: QrColors) -> QrCodeWidget: ...
    @property
    def data(self) -> str: ...

# ── Frame qrcode render method ────────────────────────────────────────────────

# NOTE: Addition to Frame class:
# class Frame (additions):
#     def render_qrcode(self, qr: QrCodeWidget, area: Rect) -> None: ...

# ═══════════════════════════════════════════════════════════════════════════════
# Calendar  (ratatui widget-calendar integration)
# ═══════════════════════════════════════════════════════════════════════════════

class CalendarDate:
    """A calendar date (year, month 1-12, day).

    Example::

        from pyratatui import CalendarDate
        today = CalendarDate.today()
        d     = CalendarDate.from_ymd(2024, 3, 15)
    """

    @staticmethod
    def from_ymd(year: int, month: int, day: int) -> CalendarDate:
        """Construct from year, month (1-12), and day. Raises ValueError for invalid dates."""
        ...

    @staticmethod
    def today() -> CalendarDate:
        """Return today's UTC date."""
        ...

    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CalendarEventStore:
    """Event store for the calendar widget: maps dates to display styles.

    Example::

        from pyratatui import CalendarDate, CalendarEventStore, Style, Color

        store = CalendarEventStore()
        store.add(CalendarDate.from_ymd(2024, 3, 15), Style().fg(Color.red()).bold())
        store.add_today(Style().fg(Color.green()).bold())
    """

    def __init__(self) -> None: ...
    def add(self, date: CalendarDate, style: Style) -> None:
        """Mark *date* with *style* in the event store."""
        ...

    def add_today(self, style: Style) -> None:
        """Highlight today's date with *style*."""
        ...

    @staticmethod
    def today_highlighted(style: Style) -> CalendarEventStore:
        """Return a new store with today already highlighted."""
        ...

    def __repr__(self) -> str: ...

class Monthly:
    """Monthly calendar widget.

    Displays a full month calendar with optional event styling, surrounding
    days, weekday headers, and a month/year title.

    Example::

        from pyratatui import CalendarDate, CalendarEventStore, Monthly, Style, Color

        store = CalendarEventStore.today_highlighted(Style().fg(Color.green()).bold())
        cal   = (Monthly(CalendarDate.today(), store)
                    .show_month_header(Style().bold())
                    .show_weekdays_header(Style().italic())
                    .show_surrounding(Style().dim()))
        # frame.render_widget(cal, area)
    """

    def __init__(
        self, display_date: CalendarDate, events: CalendarEventStore
    ) -> None: ...
    def block(self, block: Block) -> Monthly:
        """Wrap in a ``Block``."""
        ...

    def default_style(self, style: Style) -> Monthly:
        """Style applied to all unstyled days."""
        ...

    def show_surrounding(self, style: Style) -> Monthly:
        """Show days from adjacent months in *style*."""
        ...

    def show_month_header(self, style: Style) -> Monthly:
        """Show the month/year header line in *style*."""
        ...

    def show_weekdays_header(self, style: Style) -> Monthly:
        """Show the weekday abbreviation header in *style*."""
        ...

    def __repr__(self) -> str: ...

# ── BarGraph (tui-bar-graph) ──────────────────────────────────────────────────

class BarGraphStyle:
    """Bar rendering style.

    Use as class attributes: ``BarGraphStyle.Braille``, etc.
    """

    Braille: BarGraphStyle
    HalfBlock: BarGraphStyle
    Block: BarGraphStyle
    Quadrant: BarGraphStyle
    Octant: BarGraphStyle
    def __repr__(self) -> str: ...

class BarColorMode:
    """Bar colour mode.

    Use as class attributes: ``BarColorMode.VerticalGradient``, etc.
    """

    VerticalGradient: BarColorMode
    HorizontalGradient: BarColorMode
    Bar: BarColorMode
    def __repr__(self) -> str: ...

class BarGraph:
    """Colourful bar graph widget.

    Example::

        from pyratatui import BarGraph, BarGraphStyle, BarColorMode

        graph = (
            BarGraph([0.1, 0.5, 0.9])
            .bar_style(BarGraphStyle.Braille)
            .color_mode(BarColorMode.VerticalGradient)
            .gradient("turbo")
        )
        frame.render_widget(graph, area)
    """

    def __init__(self, data: list[float]) -> None: ...
    @property
    def len(self) -> int: ...
    def bar_style(self, style: BarGraphStyle) -> BarGraph: ...
    def color_mode(self, mode: BarColorMode) -> BarGraph: ...
    def gradient(self, name: str) -> BarGraph: ...
    def data(self, values: list[float]) -> BarGraph: ...
    def __repr__(self) -> str: ...

# ── TreeWidget (tui-tree-widget) ───────────────────────────────────────────────

class TreeItem:
    """A node in a tree widget.

    Example::

        root = TreeItem("Root", [TreeItem("Child 1"), TreeItem("Child 2")])
    """

    def __init__(self, text: str, children: list[TreeItem] | None = None) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def children(self) -> list[TreeItem]: ...
    def with_child(self, child: TreeItem) -> TreeItem: ...
    def __repr__(self) -> str: ...

class Tree:
    """Tree-view widget.

    Example::

        tree = Tree(items).block(Block().bordered().title(" Files "))
        frame.render_stateful_tree(tree, area, state)
    """

    def __init__(self, items: list[TreeItem]) -> None: ...
    @property
    def len(self) -> int: ...
    def block(self, block: Block) -> Tree: ...
    def highlight_style(self, style: Style) -> Tree: ...
    def highlight_symbol(self, sym: str) -> Tree: ...
    def __repr__(self) -> str: ...

class TreeState:
    """Navigation state for a tree widget."""

    def __init__(self) -> None: ...
    def set_items(self, items: list[TreeItem]) -> None: ...
    @property
    def selected(self) -> list[int] | None: ...
    def select(self, path: list[int]) -> None: ...
    def open(self, path: list[int]) -> bool: ...
    def close(self, path: list[int]) -> bool: ...
    def toggle(self, path: list[int]) -> bool: ...
    def toggle_selected(self) -> bool: ...
    def key_up(self) -> bool: ...
    def key_down(self) -> bool: ...
    def key_left(self) -> bool: ...
    def key_right(self) -> bool: ...
    def __repr__(self) -> str: ...

# ── Markdown (tui-markdown) ────────────────────────────────────────────────────

def markdown_to_text(src: str) -> Text:
    """Convert a Markdown string to a ``Text`` object for rendering.

    Example::

        text = markdown_to_text("# Hello\\n\\n**bold** _italic_")
        frame.render_widget(Paragraph(text), area)
    """
    ...

# ── Logger (tui-logger) ────────────────────────────────────────────────────────

def init_logger(level: str = "info") -> None:
    """Initialise the tui-logger backend.

    Valid levels: ``"error"``, ``"warn"``, ``"info"``, ``"debug"``, ``"trace"``.
    """
    ...

def log_message(level: str, message: str) -> None:
    """Emit a log message at the given level."""
    ...

class TuiWidgetState:
    """Filter/navigation state for ``TuiLoggerWidget``."""

    def __init__(self) -> None: ...
    def transition(self, key: str) -> None: ...
    def __repr__(self) -> str: ...

class TuiLoggerWidget:
    """Scrolling log-viewer widget.

    Example::

        logger = TuiLoggerWidget().block(Block().bordered())
        state = TuiWidgetState()
        frame.render_logger(logger, area, state)
    """

    def __init__(self) -> None: ...
    def block(self, block: Block) -> TuiLoggerWidget: ...
    def style(self, style: Style) -> TuiLoggerWidget: ...
    def error_style(self, style: Style) -> TuiLoggerWidget: ...
    def warn_style(self, style: Style) -> TuiLoggerWidget: ...
    def info_style(self, style: Style) -> TuiLoggerWidget: ...
    def debug_style(self, style: Style) -> TuiLoggerWidget: ...
    def trace_style(self, style: Style) -> TuiLoggerWidget: ...
    def __repr__(self) -> str: ...

# ── Image (ratatui-image) ──────────────────────────────────────────────────────

class ImageState:
    """Mutable render state for a loaded image."""

    @property
    def path(self) -> str: ...
    def __repr__(self) -> str: ...

class ImagePicker:
    """Detects terminal graphics capabilities and creates image protocols.

    Example::

        picker = ImagePicker.halfblocks()
        state  = picker.load("photo.png")
        frame.render_stateful_image(ImageWidget(), area, state)
    """

    @staticmethod
    def halfblocks() -> ImagePicker: ...
    @staticmethod
    def with_font_size(width_px: int, height_px: int) -> ImagePicker: ...
    def load(self, path: str) -> ImageState: ...
    def __repr__(self) -> str: ...

class ImageWidget:
    """Resizing stateful image widget."""

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
