"""
pyratatui type stubs.

This file provides complete type information for IDEs and type checkers.
"""

from __future__ import annotations
from typing import Callable, Iterator, AsyncIterator, Optional, List as _List, overload

# ── Module metadata ──────────────────────────────────────────────────────────

__version__: str
__ratatui_version__: str

# ── Exceptions ───────────────────────────────────────────────────────────────

class PyratatuiError(Exception): ...
class BackendError(PyratatuiError): ...
class LayoutError(PyratatuiError): ...
class RenderError(PyratatuiError): ...
class AsyncError(PyratatuiError): ...
class StyleError(PyratatuiError): ...

# ── Color ────────────────────────────────────────────────────────────────────

class Color:
    @staticmethod
    def reset() -> Color: ...
    @staticmethod
    def black() -> Color: ...
    @staticmethod
    def red() -> Color: ...
    @staticmethod
    def green() -> Color: ...
    @staticmethod
    def yellow() -> Color: ...
    @staticmethod
    def blue() -> Color: ...
    @staticmethod
    def magenta() -> Color: ...
    @staticmethod
    def cyan() -> Color: ...
    @staticmethod
    def gray() -> Color: ...
    @staticmethod
    def dark_gray() -> Color: ...
    @staticmethod
    def light_red() -> Color: ...
    @staticmethod
    def light_green() -> Color: ...
    @staticmethod
    def light_yellow() -> Color: ...
    @staticmethod
    def light_blue() -> Color: ...
    @staticmethod
    def light_magenta() -> Color: ...
    @staticmethod
    def light_cyan() -> Color: ...
    @staticmethod
    def white() -> Color: ...
    @staticmethod
    def indexed(index: int) -> Color: ...
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Color: ...

# ── Modifier ─────────────────────────────────────────────────────────────────

class Modifier:
    def __init__(self) -> None: ...
    @staticmethod
    def bold() -> Modifier: ...
    @staticmethod
    def dim() -> Modifier: ...
    @staticmethod
    def italic() -> Modifier: ...
    @staticmethod
    def underlined() -> Modifier: ...
    @staticmethod
    def slow_blink() -> Modifier: ...
    @staticmethod
    def rapid_blink() -> Modifier: ...
    @staticmethod
    def reversed() -> Modifier: ...
    @staticmethod
    def hidden() -> Modifier: ...
    @staticmethod
    def crossed_out() -> Modifier: ...
    def __or__(self, other: Modifier) -> Modifier: ...
    def __and__(self, other: Modifier) -> Modifier: ...

# ── Style ────────────────────────────────────────────────────────────────────

class Style:
    def __init__(self) -> None: ...
    def fg(self, color: Color) -> Style: ...
    def bg(self, color: Color) -> Style: ...
    def add_modifier(self, modifier: Modifier) -> Style: ...
    def remove_modifier(self, modifier: Modifier) -> Style: ...
    def patch(self, other: Style) -> Style: ...
    def bold(self) -> Style: ...
    def italic(self) -> Style: ...
    def underlined(self) -> Style: ...
    def dim(self) -> Style: ...
    def reversed(self) -> Style: ...
    def hidden(self) -> Style: ...
    def crossed_out(self) -> Style: ...
    def slow_blink(self) -> Style: ...
    def rapid_blink(self) -> Style: ...
    @property
    def foreground(self) -> Optional[Color]: ...
    @property
    def background(self) -> Optional[Color]: ...

# ── Text primitives ───────────────────────────────────────────────────────────

class Span:
    def __init__(self, content: str, style: Optional[Style] = None) -> None: ...
    @property
    def content(self) -> str: ...
    @property
    def style(self) -> Optional[Style]: ...
    def styled(self, style: Style) -> Span: ...
    def width(self) -> int: ...

class Line:
    def __init__(self, spans: Optional[_List[Span]] = None, style: Optional[Style] = None) -> None: ...
    @staticmethod
    def from_string(s: str) -> Line: ...
    def left_aligned(self) -> Line: ...
    def centered(self) -> Line: ...
    def right_aligned(self) -> Line: ...
    def styled(self, style: Style) -> Line: ...
    def push_span(self, span: Span) -> None: ...
    @property
    def spans(self) -> _List[Span]: ...
    def width(self) -> int: ...

class Text:
    def __init__(self, lines: Optional[_List[Line]] = None, style: Optional[Style] = None) -> None: ...
    @staticmethod
    def from_string(s: str) -> Text: ...
    def push_line(self, line: Line) -> None: ...
    def push_str(self, s: str) -> None: ...
    @property
    def height(self) -> int: ...
    def width(self) -> int: ...
    def centered(self) -> Text: ...
    def right_aligned(self) -> Text: ...
    def styled(self, style: Style) -> Text: ...
    @property
    def lines(self) -> _List[Line]: ...

# ── Layout ────────────────────────────────────────────────────────────────────

class Rect:
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def bottom(self) -> int: ...
    @property
    def left(self) -> int: ...
    @property
    def top(self) -> int: ...
    def area(self) -> int: ...
    def is_empty(self) -> bool: ...
    def inner(self, horizontal: int = 1, vertical: int = 1) -> Rect: ...
    def contains(self, other: Rect) -> bool: ...
    def intersection(self, other: Rect) -> Optional[Rect]: ...
    def union(self, other: Rect) -> Rect: ...

class Constraint:
    @staticmethod
    def length(n: int) -> Constraint: ...
    @staticmethod
    def percentage(pct: int) -> Constraint: ...
    @staticmethod
    def fill(n: int) -> Constraint: ...
    @staticmethod
    def min(n: int) -> Constraint: ...
    @staticmethod
    def max(n: int) -> Constraint: ...
    @staticmethod
    def ratio(numerator: int, denominator: int) -> Constraint: ...

class Direction:
    Horizontal: Direction
    Vertical: Direction

class Alignment:
    Left: Alignment
    Center: Alignment
    Right: Alignment

class Layout:
    def __init__(self) -> None: ...
    def constraints(self, constraints: _List[Constraint]) -> Layout: ...
    def direction(self, direction: Direction) -> Layout: ...
    def margin(self, margin: int) -> Layout: ...
    def spacing(self, spacing: int) -> Layout: ...
    def flex_mode(self, mode: str) -> Layout: ...
    def split(self, area: Rect) -> _List[Rect]: ...

# ── Buffer ────────────────────────────────────────────────────────────────────

class Buffer:
    def __init__(self, area: Rect) -> None: ...
    @property
    def area(self) -> Rect: ...
    def set_string(self, x: int, y: int, text: str, style: Optional[Style] = None) -> None: ...
    def set_span(self, x: int, y: int, span: Span) -> None: ...
    def get_string(self, x: int, y: int, width: int) -> str: ...
    def reset(self) -> None: ...
    def merge(self, other: Buffer) -> None: ...

# ── Widgets ───────────────────────────────────────────────────────────────────

class BorderType:
    Plain: BorderType
    Rounded: BorderType
    Double: BorderType
    Thick: BorderType
    QuadrantInside: BorderType
    QuadrantOutside: BorderType

class Block:
    def __init__(self) -> None: ...
    def title(self, title: str) -> Block: ...
    def title_bottom(self, title: str) -> Block: ...
    def bordered(self) -> Block: ...
    def borders(self, top: bool = True, right: bool = True, bottom: bool = True, left: bool = True) -> Block: ...
    def border_type(self, bt: BorderType) -> Block: ...
    def style(self, style: Style) -> Block: ...
    def title_style(self, style: Style) -> Block: ...
    def border_style(self, style: Style) -> Block: ...
    def padding(self, left: int = 0, right: int = 0, top: int = 0, bottom: int = 0) -> Block: ...
    def title_alignment(self, alignment: str) -> Block: ...

class Paragraph:
    def __init__(self, text: Text) -> None: ...
    @staticmethod
    def from_string(s: str) -> Paragraph: ...
    def block(self, block: Block) -> Paragraph: ...
    def style(self, style: Style) -> Paragraph: ...
    def wrap(self, wrap: bool = True, trim: bool = True) -> Paragraph: ...
    def scroll(self, y: int = 0, x: int = 0) -> Paragraph: ...
    def alignment(self, alignment: str) -> Paragraph: ...
    def left_aligned(self) -> Paragraph: ...
    def centered(self) -> Paragraph: ...
    def right_aligned(self) -> Paragraph: ...

class ListItem:
    def __init__(self, text: str, style: Optional[Style] = None) -> None: ...
    @staticmethod
    def from_text(text: Text) -> ListItem: ...
    def style(self, style: Style) -> ListItem: ...

class ListState:
    def __init__(self) -> None: ...
    def select(self, index: Optional[int] = None) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    @property
    def selected(self) -> Optional[int]: ...
    @property
    def offset(self) -> int: ...

class ListDirection:
    TopToBottom: ListDirection
    BottomToTop: ListDirection

class List:
    def __init__(self, items: _List[ListItem]) -> None: ...
    def block(self, block: Block) -> List: ...
    def style(self, style: Style) -> List: ...
    def highlight_style(self, style: Style) -> List: ...
    def highlight_symbol(self, sym: str) -> List: ...
    def direction(self, direction: ListDirection) -> List: ...
    def repeat_highlight_symbol(self, v: bool) -> List: ...

class Cell:
    def __init__(self, text: str, style: Optional[Style] = None) -> None: ...
    def style(self, style: Style) -> Cell: ...

class Row:
    def __init__(self, cells: _List[Cell]) -> None: ...
    @staticmethod
    def from_strings(texts: _List[str]) -> Row: ...
    def style(self, style: Style) -> Row: ...
    def height(self, height: int) -> Row: ...

class TableState:
    def __init__(self) -> None: ...
    def select(self, index: Optional[int] = None) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    @property
    def selected(self) -> Optional[int]: ...
    @property
    def offset(self) -> int: ...

class Table:
    def __init__(self, rows: _List[Row], widths: _List[Constraint], header: Optional[Row] = None) -> None: ...
    def block(self, block: Block) -> Table: ...
    def style(self, style: Style) -> Table: ...
    def highlight_style(self, style: Style) -> Table: ...
    def highlight_symbol(self, sym: str) -> Table: ...
    def column_spacing(self, n: int) -> Table: ...
    def footer(self, row: Row) -> Table: ...

class Gauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> Gauge: ...
    def percent(self, pct: int) -> Gauge: ...
    def ratio(self, ratio: float) -> Gauge: ...
    def style(self, style: Style) -> Gauge: ...
    def gauge_style(self, style: Style) -> Gauge: ...
    def label(self, label: str) -> Gauge: ...
    def use_unicode(self, v: bool) -> Gauge: ...

class LineGauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> LineGauge: ...
    def ratio(self, ratio: float) -> LineGauge: ...
    def percent(self, pct: int) -> LineGauge: ...
    def style(self, style: Style) -> LineGauge: ...
    def gauge_style(self, style: Style) -> LineGauge: ...
    def label(self, label: str) -> LineGauge: ...
    def line_set(self, name: str) -> LineGauge: ...

class Bar:
    def __init__(self, value: int, label: Optional[str] = None) -> None: ...
    def style(self, style: Style) -> Bar: ...
    def value_style(self, style: Style) -> Bar: ...
    def text_value(self, tv: str) -> Bar: ...

class BarGroup:
    def __init__(self, bars: _List[Bar], label: Optional[str] = None) -> None: ...

class BarChart:
    def __init__(self) -> None: ...
    def data(self, group: BarGroup) -> BarChart: ...
    def block(self, block: Block) -> BarChart: ...
    def bar_width(self, w: int) -> BarChart: ...
    def bar_gap(self, g: int) -> BarChart: ...
    def group_gap(self, g: int) -> BarChart: ...
    def max(self, m: int) -> BarChart: ...
    def style(self, s: Style) -> BarChart: ...
    def bar_style(self, s: Style) -> BarChart: ...
    def value_style(self, s: Style) -> BarChart: ...
    def label_style(self, s: Style) -> BarChart: ...

class Sparkline:
    def __init__(self) -> None: ...
    def data(self, data: _List[int]) -> Sparkline: ...
    def block(self, block: Block) -> Sparkline: ...
    def max(self, m: int) -> Sparkline: ...
    def style(self, style: Style) -> Sparkline: ...

class Clear:
    def __init__(self) -> None: ...

class ScrollbarOrientation:
    VerticalRight: ScrollbarOrientation
    VerticalLeft: ScrollbarOrientation
    HorizontalBottom: ScrollbarOrientation
    HorizontalTop: ScrollbarOrientation

class ScrollbarState:
    def __init__(self) -> None: ...
    def content_length(self, n: int) -> ScrollbarState: ...
    def position(self, pos: int) -> ScrollbarState: ...
    def scroll_next(self) -> None: ...
    def scroll_prev(self) -> None: ...
    def first(self) -> None: ...
    def last(self) -> None: ...
    @property
    def get_position(self) -> int: ...

class Scrollbar:
    def __init__(self, orientation: Optional[ScrollbarOrientation] = None) -> None: ...
    def orientation(self, o: ScrollbarOrientation) -> Scrollbar: ...
    def thumb_style(self, st: Style) -> Scrollbar: ...
    def track_style(self, st: Style) -> Scrollbar: ...
    def begin_style(self, st: Style) -> Scrollbar: ...
    def end_style(self, st: Style) -> Scrollbar: ...

class Tabs:
    def __init__(self, titles: _List[str]) -> None: ...
    def select(self, index: int) -> Tabs: ...
    def block(self, block: Block) -> Tabs: ...
    def style(self, style: Style) -> Tabs: ...
    def highlight_style(self, style: Style) -> Tabs: ...
    def divider(self, d: str) -> Tabs: ...
    def padding(self, left: str, right: str) -> Tabs: ...

# ── Terminal & Frame ──────────────────────────────────────────────────────────

class KeyEvent:
    code: str
    ctrl: bool
    alt: bool
    shift: bool

class Frame:
    @property
    def area(self) -> Rect: ...
    @property
    def size(self) -> Rect: ...
    def render_widget(self, widget: object, area: Rect) -> None: ...
    def render_stateful_list(self, widget: List, area: Rect, state: ListState) -> None: ...
    def render_stateful_table(self, widget: Table, area: Rect, state: TableState) -> None: ...
    def render_stateful_scrollbar(self, widget: Scrollbar, area: Rect, state: ScrollbarState) -> None: ...
    def apply_effect(self, effect: Effect, elapsed_ms: int, area: Rect) -> None: ...
    def apply_effect_manager(self, manager: EffectManager, elapsed_ms: int, area: Rect) -> None: ...

class CrosstermBackend: ...

class Terminal:
    def __init__(self) -> None: ...
    def __enter__(self) -> Terminal: ...
    def __exit__(self, *args: object) -> bool: ...
    async def __aenter__(self) -> Terminal: ...
    async def __aexit__(self, *args: object) -> bool: ...
    def restore(self) -> None: ...
    def draw(self, draw_fn: Callable[[Frame], None]) -> None: ...
    def poll_event(self, timeout_ms: int = 0) -> Optional[KeyEvent]: ...
    def area(self) -> Rect: ...
    def clear(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...

# ── Python-side helpers ───────────────────────────────────────────────────────

class AsyncTerminal:
    def __init__(self) -> None: ...
    async def __aenter__(self) -> AsyncTerminal: ...
    async def __aexit__(self, *args: object) -> bool: ...
    def draw(self, draw_fn: Callable[[Frame], None]) -> None: ...
    async def poll_event(self, timeout_ms: int = 50) -> Optional[KeyEvent]: ...
    async def events(self, fps: float = 30.0, *, stop_on_quit: bool = True) -> AsyncIterator[Optional[KeyEvent]]: ...
    def area(self) -> Rect: ...
    def clear(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...

def run_app(
    ui_fn: Callable[[Frame], None],
    *,
    fps: float = 30.0,
    on_key: Optional[Callable[[KeyEvent], bool]] = None,
) -> None: ...

async def run_app_async(
    ui_fn: Callable[[Frame], None],
    *,
    fps: float = 30.0,
    on_key: Optional[Callable[[KeyEvent], bool]] = None,
) -> None: ...

# ── TachyonFX Effects ─────────────────────────────────────────────────────────

class Interpolation:
    Linear: Interpolation
    QuadIn: Interpolation; QuadOut: Interpolation; QuadInOut: Interpolation
    CubicIn: Interpolation; CubicOut: Interpolation; CubicInOut: Interpolation
    QuartIn: Interpolation; QuartOut: Interpolation; QuartInOut: Interpolation
    QuintIn: Interpolation; QuintOut: Interpolation; QuintInOut: Interpolation
    SineIn: Interpolation; SineOut: Interpolation; SineInOut: Interpolation
    CircIn: Interpolation; CircOut: Interpolation; CircInOut: Interpolation
    ExpoIn: Interpolation; ExpoOut: Interpolation; ExpoInOut: Interpolation
    ElasticIn: Interpolation; ElasticOut: Interpolation
    BounceIn: Interpolation; BounceOut: Interpolation; BounceInOut: Interpolation
    BackIn: Interpolation; BackOut: Interpolation; BackInOut: Interpolation

class Motion:
    LeftToRight: Motion
    RightToLeft: Motion
    UpToDown: Motion
    DownToUp: Motion

class EffectTimer:
    def __init__(self, duration_ms: int, interpolation: Optional[Interpolation] = None) -> None: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def interpolation(self) -> Interpolation: ...

class CellFilter:
    @staticmethod
    def all() -> CellFilter: ...
    @staticmethod
    def text() -> CellFilter: ...
    @staticmethod
    def fg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def bg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def inner(horizontal: int = 1, vertical: int = 1) -> CellFilter: ...
    @staticmethod
    def outer(horizontal: int = 1, vertical: int = 1) -> CellFilter: ...
    @staticmethod
    def all_of(filters: _List[CellFilter]) -> CellFilter: ...
    @staticmethod
    def any_of(filters: _List[CellFilter]) -> CellFilter: ...

class Effect:
    # Color transitions
    @staticmethod
    def fade_from(from_bg: Color, from_fg: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def fade_from_fg(from_color: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def fade_to(to_bg: Color, to_fg: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def fade_to_fg(to_color: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    # Text materialization
    @staticmethod
    def coalesce(duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def dissolve(duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    # Sliding
    @staticmethod
    def slide_in(direction: Motion, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def slide_out(direction: Motion, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def sweep_in(direction: Motion, sweep_span: int, gradient_len: int, color: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    @staticmethod
    def sweep_out(direction: Motion, sweep_span: int, gradient_len: int, color: Color, duration_ms: int, interpolation: Optional[Interpolation] = None) -> Effect: ...
    # Composition
    @staticmethod
    def sequence(effects: _List[Effect]) -> Effect: ...
    @staticmethod
    def parallel(effects: _List[Effect]) -> Effect: ...
    @staticmethod
    def sleep(duration_ms: int) -> Effect: ...
    @staticmethod
    def repeat(effect: Effect, times: int = -1) -> Effect: ...
    @staticmethod
    def ping_pong(effect: Effect) -> Effect: ...
    @staticmethod
    def never_complete(effect: Effect) -> Effect: ...
    # Instance methods
    def with_filter(self, filter: CellFilter) -> None: ...
    def process(self, elapsed_ms: int, buffer: Buffer, area: Rect) -> None: ...
    def done(self) -> bool: ...
    def reset(self) -> None: ...

class EffectManager:
    def __init__(self) -> None: ...
    def add(self, effect: Effect) -> None: ...
    def add_unique(self, key: str, effect: Effect) -> None: ...
    def process(self, elapsed_ms: int, buffer: Buffer, area: Rect) -> None: ...
    def active_count(self) -> int: ...
    def clear(self) -> None: ...
    def has_active(self) -> bool: ...

def compile_effect(expression: str) -> Effect: ...
