name: Cloud MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install MkDocs + Material + mkdocstrings + extensions
        run: |
          pip install --upgrade pip
          pip install "mkdocs<2.0" mkdocs-material==9.1.18 "mkdocstrings[python]" pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
          
